### ISSUE TITLE
App does not support ELAC-devices (e.g. TechniSat Audiomaster, DigitRadio etc.)

### ISSUE THREAD

**Issue by EarthlingX** [mkiol/Jupii#34] opened 2021-01-02 12:20 UTC
Thank you very much for your great efforts! :-)

Did anybody test the app with TechniSat-devices? They have this ELAC-controller included. In Jupii I can detect and connect TechniSat devices without any problems, but I can not process any further.

As soon as I try to play a specific music file or radio URL, the "waiting" circle at the item will appear, stucks after a few seconds and the app crashes.

Can I provide you some log files anyhow?

**Comment by mkiol** [comment] 2021-01-02 15:08
Thanks for the report. Yes, log would be very useful. 

To enable logging:
1. Settings -> Enable logging
2. restart app (FYI: app start resets log file)
3. do your test
4. close app
5. copy 'jupii.log' file from the phone

Log file may contain IP addresses therefore please anonymize it if it's important to you.

You can send me log via email (jupii@mkiol.net) or any other way convenient to you.

**Comment by mkiol** [comment] 2021-01-10 15:22
Let me sum up the issue investigation so far:

- [Issue root cause] When the device (TechniSat) is in "sleep" mode, UPnP request timeouts (Jupii doesn't receive any response). However when the device is waken up the issue does not occur and Jupii works as expected. 
It appears that TechniSat cannot be waken up with simple UPnP call, most likely there is a proprietary API to do this. Unfortunately I didn't find any information in the Internet about such API and how to use it :(
- Crash error is resolved in most recent release available on OpenRepos (v2.8.2).

**Comment by EarthlingX** [comment] 2021-01-10 19:15
> Let me sum up the issue investigation so far:
> 
>     * [Issue root cause] When the device (TechniSat) is in "sleep" mode, UPnP request timeouts (Jupii doesn't receive any response). However when the device is waken up the issue does not occur and Jupii works as expected.
>       It appears that TechniSat cannot be waken up with simple UPnP call, most likely there is a proprietary API to do this. Unfortunately I didn't find any information in the Internet about such API and how to use it :(
> 
>     * Crash error is resolved in most recent release available on OpenRepos (v2.8.2).

Completely correct! :+1: 

We need to investigate what kind of protocol is used to set the device into "wake up" mode. Several radios and loudspeakers use this Frontier Silicon chipset that can be controlled by Undok app.

However, Undok app has many alternatives that work the same way and use the same protocol in combination with the Frontier Silicon chipset:

- TechniSat Connect App
- RadioRemote App
- SilverCrest SMART AUDIO App

Maybe we can check one of the source codes of those apps anyhow?

**Comment by mkiol** [comment] 2021-01-11 12:04
I think I found an interesting project: https://github.com/flammy/fsapi/
It seems that someone has already reverse engineered Frontier Silicon API :)

**Comment by mkiol** [comment] 2021-01-11 12:30
Another project - python API for FSAPI: https://github.com/zhelev/python-fsapi

@EarthlingX Would you be able to check if for instance `python-fsapi` works with your device? There is `tests.py` script that can be use for testing.

**Comment by mkiol** [comment] 2021-02-04 19:22
ef10acc69e977492ef5d457fd2a81356bb9e194a
7609bd8f2411e142780c96d63f1ba47572d5031b
d09ad88d78f7a3fa5ddea2ea6cd3bc2cc9892e33
07f6e9e1e64c48b117f26f4e7c4da2eafb388386
70d7338180415f5d5ac34ea8cc22a19ce8accd57

**Comment by EarthlingX** [comment] 2021-02-04 21:28
Already excited... :+1:

**Comment by mkiol** [comment] 2021-02-21 18:29
New [release 2.9.0](https://openrepos.net/sites/default/files/packages/1804/harbour-jupii-2.9.0-2.armv7hl.rpm) with FSAPI support.

Hopefully the issue with ELAC-devices is now resolved :)

**Closed by mkiol** 2021-02-21 18:29 UTC
